import assert from "node:assert/strict";
import { after, afterEach, before, describe, it } from "node:test";
import { randomUUID } from "node:crypto";
import type { Server } from "node:http";
import jwt from "jsonwebtoken";
import { Decimal } from "@prisma/client/runtime/client";
import app from "../app.js";
import { config } from "../config/index.js";
import { prisma } from "../prisma/runtime.js";

const userIds: number[] = [], productIds: number[] = [], listingIds: number[] = [];
let server: Server; let url: string;

before(async () => { server = app.listen(0); await new Promise<void>((resolve) => server.once("listening", resolve)); const address = server.address(); if (!address || typeof address === "string") throw new Error("server address unavailable"); url = `http://localhost:${address.port}`; });
afterEach(async () => { if (userIds.length) { const carts = await prisma.cart.findMany({ where: { userId: { in: userIds } }, select: { id: true } }); if (carts.length) await prisma.cartItem.deleteMany({ where: { cartId: { in: carts.map((cart) => cart.id) } } }); await prisma.cart.deleteMany({ where: { userId: { in: userIds } } }); } if (listingIds.length) await prisma.productListing.deleteMany({ where: { id: { in: listingIds } } }); if (productIds.length) await prisma.legoProduct.deleteMany({ where: { id: { in: productIds } } }); if (userIds.length) await prisma.user.deleteMany({ where: { id: { in: userIds } } }); userIds.length = productIds.length = listingIds.length = 0; });
after(async () => { await prisma.$disconnect(); server.close(); });

async function fixture(emailVerified = false) {
  const user = await prisma.user.create({ data: { email: `${randomUUID()}@example.com`, passwordHash: "hash", emailVerified } }); userIds.push(user.id);
  const product = await prisma.legoProduct.create({ data: { setNumber: `CART-${randomUUID()}`, title: "Cart product", theme: "Test", ageRecommendation: "8+", pieceCount: 10 } }); productIds.push(product.id);
  const listing = await prisma.productListing.create({ data: { legoProductId: product.id, condition: "NEW", originalPrice: new Decimal(20), salePrice: new Decimal(15), currentStock: 10, reservedStock: 2, active: true } }); listingIds.push(listing.id);
  return { listing, token: jwt.sign({ id: user.id, role: user.role }, config.JWT_SECRET), user };
}
const request = (token: string, path: string, init: RequestInit = {}) => fetch(`${url}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...(init.headers ?? {}) } });

describe("customer cart HTTP integration", () => {
  it("allows unverified authenticated users and exposes derived price/availability", async () => { const f = await fixture(); const response = await request(f.token, "/cart"); assert.equal(response.status, 200); const body = await response.json(); assert.equal(body.userId, f.user.id); assert.deepEqual(body.items, []); });
  it("adds, updates, removes and clears items without changing stock", async () => { const f = await fixture(true); const before = await prisma.productListing.findUnique({ where: { id: f.listing.id } });
    let response = await request(f.token, "/cart/items", { method: "POST", body: JSON.stringify({ productListingId: f.listing.id, quantity: 2 }) }); assert.equal(response.status, 200); let body = await response.json(); assert.equal(body.items[0].quantity, 2); assert.equal(body.items[0].productListing.availableStock, 8); assert.equal(body.items[0].productListing.effectivePrice, "15");
    response = await request(f.token, `/cart/items/${f.listing.id}`, { method: "PATCH", body: JSON.stringify({ quantity: 1 }) }); assert.equal(response.status, 200); assert.equal((await response.json()).items[0].quantity, 1);
    response = await request(f.token, `/cart/items/${f.listing.id}`, { method: "DELETE" }); assert.equal(response.status, 200); assert.deepEqual((await response.json()).items, []);
    response = await request(f.token, "/cart", { method: "DELETE" }); assert.equal(response.status, 200); assert.deepEqual((await response.json()).items, []);
    assert.deepEqual(await prisma.productListing.findUnique({ where: { id: f.listing.id } }), before);
  });
  it("duplicate POSTs increment the existing quantity", async () => { const f = await fixture(true); await request(f.token, "/cart/items", { method: "POST", body: JSON.stringify({ productListingId: f.listing.id, quantity: 1 }) }); const response = await request(f.token, "/cart/items", { method: "POST", body: JSON.stringify({ productListingId: f.listing.id, quantity: 1 }) }); assert.equal(response.status, 200); assert.equal((await response.json()).items[0].quantity, 2); });
  it("serializes concurrent first additions and increments", async () => { const f = await fixture(true); const add = () => request(f.token, "/cart/items", { method: "POST", body: JSON.stringify({ productListingId: f.listing.id, quantity: 1 }) }); const first = await Promise.all([add(), add()]); const firstBodies = await Promise.all(first.map((response) => response.clone().json())); assert.deepEqual(first.map((response) => response.status).sort(), [200, 200], JSON.stringify(firstBodies)); let body = await (await request(f.token, "/cart")).json(); assert.equal(body.items.length, 1); assert.equal(body.items[0].quantity, 2); const second = await Promise.all([add(), add()]); assert.deepEqual(second.map((response) => response.status).sort(), [200, 200]); body = await (await request(f.token, "/cart")).json(); assert.equal(body.items[0].quantity, 4); });
  it("rejects concurrent additions that exceed available stock", async () => { const f = await fixture(true); const add = () => request(f.token, "/cart/items", { method: "POST", body: JSON.stringify({ productListingId: f.listing.id, quantity: 5 }) }); const responses = await Promise.all([add(), add()]); assert.deepEqual(responses.map((response) => response.status).sort(), [200, 409]); const body = await (await request(f.token, "/cart")).json(); assert.equal(body.items[0].quantity, 5); });
  it("isolates carts by authenticated user", async () => { const owner = await fixture(true); const other = await fixture(true); await request(owner.token, "/cart/items", { method: "POST", body: JSON.stringify({ productListingId: owner.listing.id, quantity: 1 }) }); assert.equal((await (await request(other.token, "/cart")).json()).items.length, 0); assert.equal((await request(other.token, `/cart/items/${owner.listing.id}`, { method: "PATCH", body: JSON.stringify({ quantity: 1 }) })).status, 404); assert.equal((await request(other.token, `/cart/items/${owner.listing.id}`, { method: "DELETE" })).status, 404); });
  it("maps missing and malformed item operations deterministically", async () => { const f = await fixture(true); assert.equal((await request(f.token, `/cart/items/${f.listing.id}`, { method: "PATCH", body: JSON.stringify({ quantity: 1 }) })).status, 404); assert.equal((await request(f.token, `/cart/items/${f.listing.id}`, { method: "DELETE" })).status, 404); assert.equal((await request(f.token, "/cart/items/not-an-id", { method: "PATCH", body: JSON.stringify({ quantity: 1 }) })).status, 400); assert.equal((await request(f.token, "/cart/items/not-an-id", { method: "DELETE" })).status, 400); });
  it("rejects unavailable quantities and does not remove unavailable cart items on GET", async () => { const f = await fixture(true); let response = await request(f.token, "/cart/items", { method: "POST", body: JSON.stringify({ productListingId: f.listing.id, quantity: 9 }) }); assert.equal(response.status, 409); response = await request(f.token, "/cart/items", { method: "POST", body: JSON.stringify({ productListingId: f.listing.id, quantity: 1 }) }); assert.equal(response.status, 200); await prisma.productListing.update({ where: { id: f.listing.id }, data: { active: false, currentStock: 0 } }); response = await request(f.token, "/cart"); assert.equal(response.status, 200); assert.equal((await response.json()).items.length, 1); });
  it("clamps inconsistent availability and serializes original price", async () => { const f = await fixture(true); await prisma.productListing.update({ where: { id: f.listing.id }, data: { salePrice: null } }); assert.equal((await request(f.token, "/cart/items", { method: "POST", body: JSON.stringify({ productListingId: f.listing.id, quantity: 1 }) })).status, 200); await prisma.productListing.update({ where: { id: f.listing.id }, data: { currentStock: 1, reservedStock: 2 } }); const body = await (await request(f.token, "/cart")).json(); assert.equal(body.items[0].productListing.availableStock, 0); assert.equal(body.items[0].productListing.effectivePrice, "20"); });
  it("rejects unauthenticated access", async () => { assert.equal((await fetch(`${url}/cart`)).status, 401); });
});
