import assert from "node:assert/strict";
import { afterEach, describe, it } from "node:test";
import { randomUUID } from "node:crypto";
import { Decimal } from "@prisma/client/runtime/client";
import { prisma } from "../prisma/runtime.js";
import { PaymentProvider, PaymentStatus, RefundProvider, RefundStatus } from "../generated/prisma-client/enums.js";
import { createOrReusePayPalRefund, PayPalRefundProviderError, PayPalRefundValidationError, setPayPalRefundClientForTests } from "../domain/refunds/paypalRefundService.js";

const users: number[] = [], orders: number[] = [];
afterEach(async () => { if (orders.length) await prisma.order.deleteMany({ where: { id: { in: orders } } }); if (users.length) await prisma.user.deleteMany({ where: { id: { in: users } } }); users.length = orders.length = 0; });
async function fixture(amount = "100.00", provider = PaymentProvider.PAYPAL, status = PaymentStatus.SUCCEEDED) { const u = await prisma.user.create({ data: { email: `${randomUUID()}@example.com`, passwordHash: "hash" } }); users.push(u.id); const o = await prisma.order.create({ data: { userId: u.id, billingRecipientName: "C", billingLine1: "1", billingCity: "London", billingPostcode: "AA1", billingCountryCode: "GB", deliveryRecipientName: "C", deliveryLine1: "1", deliveryCity: "London", deliveryPostcode: "AA1", deliveryCountryCode: "GB", totalAmount: new Decimal(amount) } }); orders.push(o.id); const p = await prisma.payment.create({ data: { orderId: o.id, amount: new Decimal(amount), currency: "GBP", provider, providerReference: `PP-ORDER-${randomUUID()}`, providerCaptureReference: provider === PaymentProvider.PAYPAL ? `PP-CAP-${randomUUID()}` : null, status } }); return { u, o, p }; }
function fake(status = "COMPLETED", amount = "100.00", currency = "GBP") { const calls: any[] = []; const restore = setPayPalRefundClientForTests({ refundCapture: async (captureId, requestId, value, code) => { calls.push({ captureId, requestId, value, code }); if (status === "THROW") throw new Error("timeout"); return { id: `PP-REFUND-${randomUUID()}`, status, amount: { value: amount, currency_code: currency } }; } }); return { calls, restore }; }
describe("PayPal refund service", { concurrency: 1 }, () => {
  it("creates and finalizes a full authoritative PayPal refund", async () => { const f = await fixture(); const c = fake(); const result = await createOrReusePayPalRefund(f.o.id, f.p.id, 100, "full", f.u.id); assert.equal(result.status, RefundStatus.SUCCEEDED); assert.equal(result.provider, RefundProvider.PAYPAL); assert.equal(c.calls[0].captureId, f.p.providerCaptureReference); assert.equal(c.calls[0].value, "100.00"); assert.equal(c.calls[0].code, "GBP"); assert.ok(c.calls[0].requestId); const p = await prisma.payment.findUnique({ where: { id: f.p.id } }); assert.equal(p?.refundedAmount.toString(), "100"); assert.equal(p?.reservedRefundAmount.toString(), "0"); assert.match(result.providerReference, /^PP-REFUND-/); c.restore(); });
  it("supports distinct partial refunds and prevents cumulative over-refund", async () => { const f = await fixture(); const a = fake("COMPLETED", "30.00"); const first = await createOrReusePayPalRefund(f.o.id, f.p.id, 30, undefined, f.u.id); a.restore(); const b = fake("COMPLETED", "30.00"); const second = await createOrReusePayPalRefund(f.o.id, f.p.id, 30, undefined, f.u.id); assert.notEqual(first.id, second.id); assert.notEqual(first.refundIdempotencyKey, second.refundIdempotencyKey); assert.equal(b.calls.length, 1); b.restore(); await assert.rejects(() => createOrReusePayPalRefund(f.o.id, f.p.id, 50, undefined, f.u.id)); });
  it("keeps a timed-out attempt processing and retries the same Refund", async () => { const f = await fixture(); const failed = fake("THROW"); await assert.rejects(() => createOrReusePayPalRefund(f.o.id, f.p.id, 20, undefined, f.u.id), PayPalRefundProviderError); const pending = await prisma.refund.findFirst({ where: { paymentId: f.p.id } }); const paymentBefore = await prisma.payment.findUnique({ where: { id: f.p.id } }); assert.equal(pending?.status, RefundStatus.PROCESSING); assert.equal(paymentBefore?.reservedRefundAmount.toString(), "20"); failed.restore(); const retry = fake("COMPLETED", "20.00"); const done = await createOrReusePayPalRefund(f.o.id, f.p.id, 999, undefined, f.u.id, undefined, pending!.id); assert.equal(done.id, pending!.id); assert.equal(done.status, RefundStatus.SUCCEEDED); assert.equal(retry.calls[0].requestId, pending?.refundIdempotencyKey); assert.equal(retry.calls[0].value, "20.00"); assert.equal((await prisma.payment.findUnique({ where: { id: f.p.id } }))?.refundedAmount.toString(), "20"); retry.restore(); });
  it("rejects wrong attempt relationships and terminal retries before provider", async () => { const a = await fixture(); const b = await fixture(); const c = fake(); const refund = await prisma.refund.create({ data: { orderId: a.o.id, paymentId: a.p.id, amount: 10, currency: "GBP", provider: RefundProvider.PAYPAL, providerReference: `pending-${randomUUID()}`, refundIdempotencyKey: `key-${randomUUID()}`, status: RefundStatus.PROCESSING, performedByUserId: a.u.id } }); await assert.rejects(() => createOrReusePayPalRefund(b.o.id, b.p.id, 10, undefined, b.u.id, undefined, refund.id), PayPalRefundValidationError); await prisma.refund.update({ where: { id: refund.id }, data: { status: RefundStatus.SUCCEEDED } }); await assert.doesNotReject(() => createOrReusePayPalRefund(a.o.id, a.p.id, 10, undefined, a.u.id, undefined, refund.id)); assert.equal(c.calls.length, 0); c.restore(); });
  it("releases capacity on definitive provider failure without confirming money", async () => { const f = await fixture(); const c = fake("FAILED", "10.00"); const result = await createOrReusePayPalRefund(f.o.id, f.p.id, 10, undefined, f.u.id); assert.equal(result.status, RefundStatus.FAILED); const p = await prisma.payment.findUnique({ where: { id: f.p.id } }); assert.equal(p?.reservedRefundAmount.toString(), "0"); assert.equal(p?.refundedAmount.toString(), "0"); c.restore(); });
  it("does not finalize mismatched provider responses or mutate Order", async () => { const f = await fixture(); const before = await prisma.order.findUnique({ where: { id: f.o.id }, select: { status: true } }); const c = fake("COMPLETED", "9.99", "USD"); await assert.rejects(() => createOrReusePayPalRefund(f.o.id, f.p.id, 10, undefined, f.u.id), PayPalRefundValidationError); const p = await prisma.payment.findUnique({ where: { id: f.p.id } }); assert.equal(p?.refundedAmount.toString(), "0"); assert.equal(p?.reservedRefundAmount.toString(), "10"); assert.deepEqual(await prisma.order.findUnique({ where: { id: f.o.id }, select: { status: true } }), before); c.restore(); });
  it("rejects missing capture, wrong provider, and non-successful payment", async () => { const missing = await fixture(); await prisma.payment.update({ where: { id: missing.p.id }, data: { providerCaptureReference: null } }); const c = fake(); await assert.rejects(() => createOrReusePayPalRefund(missing.o.id, missing.p.id, 1, undefined, missing.u.id), PayPalRefundValidationError); const wrong = await fixture("100", PaymentProvider.STRIPE as unknown as "PAYPAL"); await assert.rejects(() => createOrReusePayPalRefund(wrong.o.id, wrong.p.id, 1, undefined, wrong.u.id), PayPalRefundValidationError); const failed = await fixture("100", PaymentProvider.PAYPAL, PaymentStatus.FAILED as unknown as "SUCCEEDED"); await assert.rejects(() => createOrReusePayPalRefund(failed.o.id, failed.p.id, 1, undefined, failed.u.id)); assert.equal(c.calls.length, 0); c.restore(); });
});
