import assert from "node:assert/strict";
import { afterEach, describe, it } from "node:test";
import { randomUUID } from "node:crypto";
import { Decimal } from "@prisma/client/runtime/client";
import { prisma } from "../prisma/runtime.js";
import { createOrReusePayPalOrder, PayPalOrderExpiredError, PayPalOrderOwnershipError, PayPalOrderNotFoundError, PayPalProviderError, setPayPalOrderClientForTests } from "../domain/payments/paypalOrderService.js";
import { PaymentProvider, PaymentStatus } from "../generated/prisma-client/enums.js";
const users: number[] = [], orders: number[] = [];
afterEach(async () => { if (orders.length) await prisma.order.deleteMany({ where: { id: { in: orders } } }); if (users.length) await prisma.user.deleteMany({ where: { id: { in: users } } }); users.length = orders.length = 0; });
async function fixture(expired = false) { const u = await prisma.user.create({ data: { email: `${randomUUID()}@example.com`, passwordHash: "hash", emailVerified: true } }); users.push(u.id); const o = await prisma.order.create({ data: { userId: u.id, billingRecipientName: "C", billingLine1: "1 Street", billingCity: "London", billingPostcode: "SW1A 1AA", billingCountryCode: "GB", deliveryRecipientName: "C", deliveryLine1: "1 Street", deliveryCity: "London", deliveryPostcode: "SW1A 1AA", deliveryCountryCode: "GB", totalAmount: new Decimal("12.50"), reservationExpiresAt: expired ? new Date(Date.now() - 1) : new Date(Date.now() + 3600000) } }); orders.push(o.id); return { u, o }; }
function fake() { const requests: any[] = []; const restore = setPayPalOrderClientForTests({ createOrder: async (input, requestId) => { requests.push({ input, requestId }); return { id: "PAYPAL-ORDER-1", links: [{ rel: "approve", href: "https://paypal.test/approve" }] }; } }); return { requests, restore }; }
function failingFake() { const requests: string[] = []; const restore = setPayPalOrderClientForTests({ createOrder: async (_input, requestId) => { requests.push(requestId); throw new Error("provider details"); } }); return { requests, restore }; }
describe("PayPal Orders v2 create service", { concurrency: 1 }, () => {
  it("creates a pending PayPal CAPTURE order from authoritative GBP amount", async () => { const f = await fixture(); const p = fake(); const result = await createOrReusePayPalOrder(f.o.id, f.u.id); assert.equal(result.paypalOrderId, "PAYPAL-ORDER-1"); assert.equal(p.requests[0].input.intent, "CAPTURE"); assert.deepEqual(p.requests[0].input.purchase_units[0].amount, { currency_code: "GBP", value: "12.50" }); assert.equal(p.requests[0].input.purchase_units[0].custom_id, String(f.o.id)); assert.equal(p.requests[0].requestId, `order-${f.o.id}-paypal`); const payment = await prisma.payment.findUnique({ where: { orderId: f.o.id } }); assert.equal(payment?.provider, PaymentProvider.PAYPAL); assert.equal(payment?.status, PaymentStatus.PENDING); assert.equal(payment?.providerReference, "PAYPAL-ORDER-1"); assert.equal(payment?.paidAt, null); p.restore(); });
  it("reuses the local PayPal identity without another create call", async () => { const f = await fixture(); const p = fake(); await createOrReusePayPalOrder(f.o.id, f.u.id); await createOrReusePayPalOrder(f.o.id, f.u.id); assert.equal(p.requests.length, 1); p.restore(); });
  it("rejects wrong owners and expired orders before provider invocation", async () => { const f = await fixture(true); const other = await prisma.user.create({ data: { email: `${randomUUID()}@example.com`, passwordHash: "hash" } }); users.push(other.id); const p = fake(); await assert.rejects(() => createOrReusePayPalOrder(f.o.id, other.id), PayPalOrderOwnershipError); await assert.rejects(() => createOrReusePayPalOrder(f.o.id, f.u.id), PayPalOrderExpiredError); assert.equal(p.requests.length, 0); p.restore(); });
  it("does not create a second attempt for a successful payment", async () => { const f = await fixture(); await prisma.payment.create({ data: { orderId: f.o.id, amount: f.o.totalAmount, currency: "GBP", provider: PaymentProvider.PAYPAL, providerReference: "paid-order", status: PaymentStatus.SUCCEEDED, paidAt: new Date(), idempotencyKey: `paid-${randomUUID()}` } }); const p = fake(); await assert.rejects(() => createOrReusePayPalOrder(f.o.id, f.u.id)); assert.equal(p.requests.length, 0); p.restore(); });
  it("rejects a missing order before provider invocation", async () => { const p = fake(); await assert.rejects(() => createOrReusePayPalOrder(999999999, 1), PayPalOrderNotFoundError); assert.equal(p.requests.length, 0); p.restore(); });
  it("leaves a retryable attempt and reuses its PayPal request ID after failure", async () => { const f = await fixture(); const failed = failingFake(); await assert.rejects(() => createOrReusePayPalOrder(f.o.id, f.u.id), PayPalProviderError); assert.deepEqual(failed.requests, [`order-${f.o.id}-paypal`]); const stored = await prisma.payment.findUnique({ where: { orderId: f.o.id } }); assert.equal(stored?.status, PaymentStatus.PENDING); assert.match(stored?.providerReference ?? "", /^pending:/); failed.restore(); const retried = fake(); await createOrReusePayPalOrder(f.o.id, f.u.id); assert.equal(retried.requests[0].requestId, `order-${f.o.id}-paypal`); retried.restore(); });
  it("creates one local Payment under concurrent initiation", async () => { const f = await fixture(); const p = fake(); const results = await Promise.all([createOrReusePayPalOrder(f.o.id, f.u.id), createOrReusePayPalOrder(f.o.id, f.u.id)]); assert.equal(results[0].paypalOrderId, results[1].paypalOrderId); assert.equal(await prisma.payment.count({ where: { orderId: f.o.id } }), 1); p.restore(); });
});
