import assert from "node:assert/strict";
import { describe, it, afterEach } from "node:test";
import { buildPayPalRefundDiagnostic, setPayPalWebhookVerifierForTests, paypalWebhookHandler } from "../controllers/paypalWebhookController.js";

function response() { const out: { status?: number; body?: unknown } = {}; return { out, res: { status(code: number) { out.status = code; return this; }, json(body: unknown) { out.body = body; return this; }, sendStatus(code: number) { out.status = code; return this; } } as any }; }
afterEach(() => undefined);
describe("PayPal webhook boundary", () => {
  it("accepts a verified raw JSON webhook without customer authentication", async () => { const restore = setPayPalWebhookVerifierForTests(async () => true); const { out, res } = response(); await paypalWebhookHandler({ body: Buffer.from(JSON.stringify({ id: "unknown", event_type: "UNKNOWN" }), "utf8"), headers: {} } as any, res); assert.equal(out.status, 200); restore(); });
  it("rejects invalid or non-raw webhook bodies before reconciliation", async () => { const restore = setPayPalWebhookVerifierForTests(async () => false); const first = response(); await paypalWebhookHandler({ body: Buffer.from("{}"), headers: {} } as any, first.res); assert.equal(first.out.status, 400); const second = response(); await paypalWebhookHandler({ body: {}, headers: {} } as any, second.res); assert.equal(second.out.status, 400); restore(); });
  it("rejects missing PayPal transmission headers through the verifier seam", async () => { const restore = setPayPalWebhookVerifierForTests(async (_body, req) => Boolean(req.headers["paypal-transmission-id"] && req.headers["paypal-transmission-sig"] && req.headers["paypal-cert-url"] && req.headers["paypal-auth-algo"] && req.headers["paypal-transmission-time"])); const { out, res } = response(); await paypalWebhookHandler({ body: Buffer.from(JSON.stringify({ id: "missing-headers", event_type: "UNKNOWN" })), headers: {} } as any, res); assert.equal(out.status, 400); restore(); });
  it("passes the exact raw JSON bytes to verification", async () => { let received: Buffer | undefined; const restore = setPayPalWebhookVerifierForTests(async (body) => { received = body; return false; }); const raw = Buffer.from('{"id":"raw-event","event_type":"UNKNOWN"}'); const { res } = response(); await paypalWebhookHandler({ body: raw, headers: {} } as any, res); assert.deepEqual(received, raw); restore(); });
  it("builds an allow-listed diagnostic for verified refund events", () => { const diagnostic = buildPayPalRefundDiagnostic({ id: "refund-event", event_type: "PAYMENT.REFUND.PENDING", resource_type: "refund", resource: { id: "refund-id", status: "PENDING", amount: { value: "10.00", currency_code: "GBP" }, supplementary_data: { related_ids: { order_id: "order-id" } }, links: [{ rel: "self", href: "secret-url" }] } }); assert.deepEqual(diagnostic, { eventId: "refund-event", eventType: "PAYMENT.REFUND.PENDING", resourceType: "refund", resourceId: "refund-id", resourceStatus: "PENDING", amountValue: "10.00", amountCurrency: "GBP", relatedIds: { order_id: "order-id" }, resourceKeys: ["amount", "id", "links", "status", "supplementary_data"] }); assert.equal("links" in (diagnostic as object), false); });
  it("logs diagnostics only after verification and never in production", async () => { const originalInfo = console.info; const messages: unknown[] = []; console.info = (...args: unknown[]) => messages.push(args); const previousNodeEnv = process.env.NODE_ENV; try { process.env.NODE_ENV = "test"; let restore = setPayPalWebhookVerifierForTests(async () => true); const verified = response(); await paypalWebhookHandler({ body: Buffer.from(JSON.stringify({ id: "verified", event_type: "PAYMENT.CAPTURE.REFUNDED", resource: { id: "capture-id" } })), headers: {} } as any, verified.res); restore(); assert.equal(messages.length, 1); restore = setPayPalWebhookVerifierForTests(async () => false); const rejected = response(); await paypalWebhookHandler({ body: Buffer.from(JSON.stringify({ id: "unverified", event_type: "PAYMENT.CAPTURE.REFUNDED", resource: { id: "capture-id" } })), headers: {} } as any, rejected.res); restore(); assert.equal(messages.length, 1); process.env.NODE_ENV = "production"; restore = setPayPalWebhookVerifierForTests(async () => true); const production = response(); await paypalWebhookHandler({ body: Buffer.from(JSON.stringify({ id: "production", event_type: "PAYMENT.CAPTURE.REFUNDED", resource: { id: "capture-id" } })), headers: {} } as any, production.res); restore(); assert.equal(messages.length, 1); } finally { console.info = originalInfo; if (previousNodeEnv === undefined) delete process.env.NODE_ENV; else process.env.NODE_ENV = previousNodeEnv; } });
});
