import assert from "node:assert/strict";
import { after, afterEach, before, describe, it } from "node:test";
import type { Server } from "node:http";
import { randomUUID } from "node:crypto";
import bcrypt from "bcrypt";
import jwt from "jsonwebtoken";
import { Decimal } from "@prisma/client/runtime/client";
import app from "../app.js";
import { config } from "../config/index.js";
import { prisma } from "../prisma/runtime.js";
import { PaymentProvider, PaymentStatus } from "../generated/prisma-client/enums.js";
import { setPayPalOrderClientForTests } from "../domain/payments/paypalOrderService.js";
import { setPayPalCaptureClientForTests } from "../domain/payments/paypalCaptureService.js";

let server: Server; let base = ""; let restore: (() => void)[] = []; const users: number[] = [], orders: number[] = [];
before(async () => { server = app.listen(0); await new Promise<void>((resolve) => server.once("listening", resolve)); base = `http://localhost:${(server.address() as { port: number }).port}`; });
after(async () => { await prisma.$disconnect(); server.close(); });
afterEach(async () => { restore.splice(0).forEach((fn) => fn()); if (orders.length) await prisma.order.deleteMany({ where: { id: { in: orders } } }); if (users.length) await prisma.user.deleteMany({ where: { id: { in: users } } }); orders.length = users.length = 0; });
async function fixture(verified = true, expired = false) { const u = await prisma.user.create({ data: { email: `${randomUUID()}@example.com`, passwordHash: await bcrypt.hash("Abcdef1!", 4), emailVerified: verified } }); users.push(u.id); const o = await prisma.order.create({ data: { userId: u.id, billingRecipientName: "C", billingLine1: "1 Street", billingCity: "London", billingPostcode: "SW1A 1AA", billingCountryCode: "GB", deliveryRecipientName: "C", deliveryLine1: "1 Street", deliveryCity: "London", deliveryPostcode: "SW1A 1AA", deliveryCountryCode: "GB", totalAmount: new Decimal("12.50"), reservationExpiresAt: expired ? new Date(Date.now() - 1000) : new Date(Date.now() + 3600000) } }); orders.push(o.id); return { u, o }; }
function token(id: number, role = "CUSTOMER") { return jwt.sign({ id, role }, config.JWT_SECRET, { expiresIn: "1h" }); }
function headers(id: number) { return { Authorization: `Bearer ${token(id)}`, "Content-Type": "application/json" }; }
function createFake(fail = false) { const calls: any[] = []; restore.push(setPayPalOrderClientForTests({ createOrder: async (input, requestId) => { calls.push({ input, requestId }); if (fail) throw new Error("oauth token/provider secret"); return { id: `PP-${randomUUID()}`, links: [{ rel: "approve", href: "https://paypal.test/approve" }] }; } })); return calls; }
function captureFake(fail = false) { const calls: any[] = []; restore.push(setPayPalCaptureClientForTests({ captureOrder: async (orderId, requestId) => { calls.push({ orderId, requestId }); if (fail) throw new Error("provider credentials"); return { id: orderId, status: "COMPLETED", purchase_units: [{ payments: { captures: [{ id: `CAP-${randomUUID()}`, status: "COMPLETED", amount: { value: "12.50", currency_code: "GBP" } }] } }] }; } })); return calls; }
describe("PayPal customer payment HTTP", { concurrency: 1 }, () => {
  it("creates PayPal order for verified owner and ignores financial body fields", async () => { const f = await fixture(); const calls = createFake(); const r = await fetch(`${base}/orders/${f.o.id}/payments/paypal`, { method: "POST", headers: headers(f.u.id), body: JSON.stringify({ amount: "0.01", currency: "USD", paypalOrderId: "ATTACK", captureId: "ATTACK" }) }); assert.equal(r.status, 201); const body = await r.json(); assert.ok(body.paypalOrderId); assert.equal(body.approvalUrl, "https://paypal.test/approve"); assert.equal(calls[0].input.purchase_units[0].amount.value, "12.50"); assert.equal(calls[0].input.purchase_units[0].amount.currency_code, "GBP"); assert.equal(await prisma.payment.count({ where: { orderId: f.o.id } }), 1); });
  it("enforces auth, verification, ownership, expiry, and sanitized provider errors", async () => { const f = await fixture(false); assert.equal((await fetch(`${base}/orders/${f.o.id}/payments/paypal`, { method: "POST" })).status, 401); createFake(); assert.equal((await fetch(`${base}/orders/${f.o.id}/payments/paypal`, { method: "POST", headers: headers(f.u.id) })).status, 403); const other = await fixture(); createFake(); assert.equal((await fetch(`${base}/orders/${f.o.id}/payments/paypal`, { method: "POST", headers: headers(other.u.id) })).status, 404); const expired = await fixture(true, true); createFake(); assert.equal((await fetch(`${base}/orders/${expired.o.id}/payments/paypal`, { method: "POST", headers: headers(expired.u.id) })).status, 409); const failure = await fixture(); createFake(true); const response = await fetch(`${base}/orders/${failure.o.id}/payments/paypal`, { method: "POST", headers: headers(failure.u.id) }); assert.equal(response.status, 503); assert.equal((await response.text()).includes("oauth token"), false); });
  it("reuses the same create attempt on retry", async () => { const f = await fixture(); const calls = createFake(); const h = headers(f.u.id); assert.equal((await fetch(`${base}/orders/${f.o.id}/payments/paypal`, { method: "POST", headers: h })).status, 201); assert.equal((await fetch(`${base}/orders/${f.o.id}/payments/paypal`, { method: "POST", headers: h })).status, 201); assert.equal(calls.length, 1); });
  it("captures for the owner and ignores client Capture/payment fields", async () => { const f = await fixture(); await prisma.payment.create({ data: { orderId: f.o.id, amount: f.o.totalAmount, currency: "GBP", provider: PaymentProvider.PAYPAL, providerReference: `PP-${randomUUID()}`, status: PaymentStatus.PENDING } }); const calls = captureFake(); const r = await fetch(`${base}/orders/${f.o.id}/payments/paypal/capture`, { method: "POST", headers: headers(f.u.id), body: JSON.stringify({ amount: "0.01", currency: "USD", paypalOrderId: "ATTACK", captureId: "ATTACK" }) }); assert.equal(r.status, 200); const body = await r.json(); assert.ok(body.paypalOrderId); assert.ok(body.captureId); assert.equal(calls.length, 1); });
  it("blocks capture before provider for unauthenticated, unverified, wrong-owner, expired, and provider failure cases", async () => { const f = await fixture(false); assert.equal((await fetch(`${base}/orders/${f.o.id}/payments/paypal/capture`, { method: "POST" })).status, 401); createFake(); assert.equal((await fetch(`${base}/orders/${f.o.id}/payments/paypal/capture`, { method: "POST", headers: headers(f.u.id) })).status, 403); const other = await fixture(); createFake(); assert.equal((await fetch(`${base}/orders/${f.o.id}/payments/paypal/capture`, { method: "POST", headers: headers(other.u.id) })).status, 404); const expired = await fixture(true, true); const calls = captureFake(); assert.equal((await fetch(`${base}/orders/${expired.o.id}/payments/paypal/capture`, { method: "POST", headers: headers(expired.u.id) })).status, 409); assert.equal(calls.length, 0); const failure = await fixture(); await prisma.payment.create({ data: { orderId: failure.o.id, amount: failure.o.totalAmount, currency: "GBP", provider: PaymentProvider.PAYPAL, providerReference: `PP-${randomUUID()}`, status: PaymentStatus.PENDING } }); captureFake(true); const response = await fetch(`${base}/orders/${failure.o.id}/payments/paypal/capture`, { method: "POST", headers: headers(failure.u.id) }); assert.equal(response.status, 503); assert.equal((await response.text()).includes("provider credentials"), false); });
});
