import assert from "node:assert/strict";
import { afterEach, describe, it } from "node:test";
import { randomUUID } from "node:crypto";
import { Decimal } from "@prisma/client/runtime/client";
import { prisma } from "../prisma/runtime.js";
import { PaymentProvider, PaymentStatus } from "../generated/prisma-client/enums.js";
import { capturePayPalOrder, PayPalCaptureExpiredError, PayPalCaptureMismatchError, PayPalCapturePaymentNotFoundError, PayPalCaptureOwnershipError, PayPalCaptureOrderNotFoundError, PayPalCaptureWrongProviderError, PayPalCaptureProviderError, setPayPalCaptureClientForTests } from "../domain/payments/paypalCaptureService.js";
const users: number[] = [], orders: number[] = [];
afterEach(async () => { if (orders.length) await prisma.order.deleteMany({ where: { id: { in: orders } } }); if (users.length) await prisma.user.deleteMany({ where: { id: { in: users } } }); users.length = orders.length = 0; });
async function fixture(expired = false, provider = PaymentProvider.PAYPAL) { const u = await prisma.user.create({ data: { email: `${randomUUID()}@example.com`, passwordHash: "hash", emailVerified: true } }); users.push(u.id); const o = await prisma.order.create({ data: { userId: u.id, billingRecipientName: "C", billingLine1: "1 Street", billingCity: "London", billingPostcode: "SW1A 1AA", billingCountryCode: "GB", deliveryRecipientName: "C", deliveryLine1: "1 Street", deliveryCity: "London", deliveryPostcode: "SW1A 1AA", deliveryCountryCode: "GB", totalAmount: new Decimal("12.50"), reservationExpiresAt: expired ? new Date(Date.now() - 1) : new Date(Date.now() + 3600000) } }); orders.push(o.id); const p = await prisma.payment.create({ data: { orderId: o.id, amount: o.totalAmount, currency: "GBP", provider, providerReference: `PAYPAL-ORDER-${randomUUID()}`, status: PaymentStatus.PENDING } }); return { u, o, p }; }
function fake(status = "COMPLETED", amount = "12.50", currency = "GBP") { const requests: any[] = []; const captureId = `CAPTURE-${randomUUID()}`; const restore = setPayPalCaptureClientForTests({ captureOrder: async (orderId, requestId) => { requests.push({ orderId, requestId }); return { id: orderId, status, purchase_units: [{ payments: { captures: [{ id: captureId, status, amount: { value: amount, currency_code: currency } }] } }] }; } }); return { requests, restore, captureId }; }
describe("PayPal capture service", { concurrency: 1 }, () => {
  it("captures successfully and preserves PayPal Order ID", async () => { const f = await fixture(); const c = fake(); const result = await capturePayPalOrder(f.o.id, f.u.id); assert.equal(result.captureId, c.captureId); assert.deepEqual(c.requests[0], { orderId: f.p.providerReference, requestId: `order-${f.o.id}-paypal-capture` }); const p = await prisma.payment.findUnique({ where: { id: f.p.id } }); assert.equal(p?.status, PaymentStatus.SUCCEEDED); assert.ok(p?.paidAt); assert.equal(p?.providerReference, f.p.providerReference); assert.equal(p?.providerCaptureReference, c.captureId); assert.equal(p?.captureIdempotencyKey, `order-${f.o.id}-paypal-capture`); c.restore(); });
  it("rejects invalid local state before provider invocation", async () => { const missing = fake(); await assert.rejects(() => capturePayPalOrder(999999999, 1), PayPalCaptureOrderNotFoundError); assert.equal(missing.requests.length, 0); missing.restore(); const f = await fixture(true); const other = await prisma.user.create({ data: { email: `${randomUUID()}@example.com`, passwordHash: "hash" } }); users.push(other.id); const c = fake(); await assert.rejects(() => capturePayPalOrder(f.o.id, other.id), PayPalCaptureOwnershipError); await assert.rejects(() => capturePayPalOrder(f.o.id, f.u.id), PayPalCaptureExpiredError); assert.equal(c.requests.length, 0); assert.equal((await prisma.payment.findUnique({ where: { id: f.p.id } }))?.status, PaymentStatus.PENDING); c.restore(); });
  it("rejects missing, wrong-provider, and already-successful payments", async () => { const f = await fixture(); await prisma.payment.delete({ where: { id: f.p.id } }); const c = fake(); await assert.rejects(() => capturePayPalOrder(f.o.id, f.u.id), PayPalCapturePaymentNotFoundError); c.restore(); const g = await fixture(); await prisma.payment.update({ where: { id: g.p.id }, data: { provider: PaymentProvider.STRIPE } }); const d = fake(); await assert.rejects(() => capturePayPalOrder(g.o.id, g.u.id), PayPalCaptureWrongProviderError); d.restore(); const h = await fixture(); await prisma.payment.update({ where: { id: h.p.id }, data: { status: PaymentStatus.SUCCEEDED, paidAt: new Date() } }); const e = fake(); await assert.rejects(() => capturePayPalOrder(h.o.id, h.u.id)); assert.equal(e.requests.length, 0); e.restore(); });
  it("validates completed status, amount, currency, and provider identity", async () => { const f = await fixture(); const bad = fake("COMPLETED", "99.00"); await assert.rejects(() => capturePayPalOrder(f.o.id, f.u.id), PayPalCaptureMismatchError); assert.equal((await prisma.payment.findUnique({ where: { id: f.p.id } }))?.status, PaymentStatus.PENDING); bad.restore(); const g = await fixture(); const wrong = setPayPalCaptureClientForTests({ captureOrder: async () => ({ id: "OTHER", status: "COMPLETED", purchase_units: [{ payments: { captures: [{ id: "C", status: "COMPLETED", amount: { value: "12.50", currency_code: "USD" } }] } }] }) }); await assert.rejects(() => capturePayPalOrder(g.o.id, g.u.id), PayPalCaptureMismatchError); wrong(); });
  it("uses the same capture request ID when the provider fails then succeeds", async () => { const f = await fixture(); const requests: string[] = []; const paypalOrderId = f.p.providerReference; let attempt = 0; const restore = setPayPalCaptureClientForTests({ captureOrder: async (_id, requestId) => { requests.push(requestId); if (++attempt === 1) throw new Error("timeout"); return { id: paypalOrderId, status: "COMPLETED", purchase_units: [{ payments: { captures: [{ id: `CAPTURE-${randomUUID()}`, status: "COMPLETED", amount: { value: "12.50", currency_code: "GBP" } }] } }] }; } }); await assert.rejects(() => capturePayPalOrder(f.o.id, f.u.id), PayPalCaptureProviderError); await capturePayPalOrder(f.o.id, f.u.id); assert.deepEqual(requests, [`order-${f.o.id}-paypal-capture`, `order-${f.o.id}-paypal-capture`]); restore(); });
  it("does not double-capture concurrent requests", async () => { const f = await fixture(); const c = fake(); const [a, b] = await Promise.all([capturePayPalOrder(f.o.id, f.u.id), capturePayPalOrder(f.o.id, f.u.id)]); assert.equal(a.captureId, b.captureId); assert.equal(c.requests.length, 1); assert.equal(await prisma.payment.count({ where: { orderId: f.o.id } }), 1); c.restore(); });
  it("records late success without changing expired order state or inventory", async () => { const f = await fixture(); await prisma.order.update({ where: { id: f.o.id }, data: { status: "EXPIRED" } }); const c = fake(); await assert.rejects(() => capturePayPalOrder(f.o.id, f.u.id), PayPalCaptureExpiredError); assert.equal(c.requests.length, 0); c.restore(); });
});
