import assert from "node:assert/strict";
import { afterEach, describe, it } from "node:test";
import { randomUUID } from "node:crypto";
import { Decimal } from "@prisma/client/runtime/client";
import { prisma } from "../prisma/runtime.js";
import { OrderStatus, PaymentProvider, PaymentStatus } from "../generated/prisma-client/enums.js";
import { reconcilePayPalWebhookEvent } from "../domain/payments/paypalReconciliationService.js";

const ids: { user?: number; order?: number; payment?: number } = {};
afterEach(async () => { if (ids.order) await prisma.order.delete({ where: { id: ids.order } }).catch(() => undefined); if (ids.user) await prisma.user.delete({ where: { id: ids.user } }).catch(() => undefined); ids.user = ids.order = ids.payment = undefined; });
async function fixture(expired = false, status = PaymentStatus.PROCESSING) { const u = await prisma.user.create({ data: { email: `${randomUUID()}@example.com`, passwordHash: "hash" } }); ids.user = u.id; const o = await prisma.order.create({ data: { userId: u.id, status: expired ? OrderStatus.EXPIRED : OrderStatus.PENDING, billingRecipientName: "C", billingLine1: "1 Street", billingCity: "London", billingPostcode: "SW1A 1AA", billingCountryCode: "GB", deliveryRecipientName: "C", deliveryLine1: "1 Street", deliveryCity: "London", deliveryPostcode: "SW1A 1AA", deliveryCountryCode: "GB", totalAmount: new Decimal("12.50"), reservationExpiresAt: expired ? new Date(Date.now() - 1000) : new Date(Date.now() + 3600000) } }); ids.order = o.id; const p = await prisma.payment.create({ data: { orderId: o.id, amount: o.totalAmount, currency: "GBP", provider: PaymentProvider.PAYPAL, providerReference: `PP-ORDER-${randomUUID()}`, providerCaptureReference: `PP-CAP-${randomUUID()}`, status } }); ids.payment = p.id; return { u, o, p }; }
const event = (f: Awaited<ReturnType<typeof fixture>>, type: string, overrides = {}) => ({ id: `PP-EVENT-${randomUUID()}`, eventType: type, captureId: f.p.providerCaptureReference!, paypalOrderId: f.p.providerReference, amount: "12.50", currency: "GBP", ...overrides });
describe("PayPal reconciliation", { concurrency: 1 }, () => {
  it("accepts completed captures and preserves both provider identities", async () => { const f = await fixture(); const e = event(f, "PAYMENT.CAPTURE.COMPLETED"); const r = await reconcilePayPalWebhookEvent(e); assert.equal(r.handled, true); const p = await prisma.payment.findUnique({ where: { id: f.p.id } }); assert.equal(p?.status, PaymentStatus.SUCCEEDED); assert.ok(p?.paidAt); assert.equal(p?.providerReference, f.p.providerReference); assert.equal(p?.providerCaptureReference, f.p.providerCaptureReference); });
  it("records mismatches, unknown events, and deduplicates deliveries", async () => { const f = await fixture(); const bad = event(f, "PAYMENT.CAPTURE.COMPLETED", { amount: "99.00" }); assert.equal((await reconcilePayPalWebhookEvent(bad)).handled, false); assert.equal((await prisma.payment.findUnique({ where: { id: f.p.id } }))?.status, PaymentStatus.PROCESSING); assert.ok((await prisma.paymentWebhookEvent.findUnique({ where: { provider_providerEventId: { provider: PaymentProvider.PAYPAL, providerEventId: bad.id } } }))?.processingError); assert.equal((await reconcilePayPalWebhookEvent({ ...bad, id: `UNKNOWN-${randomUUID()}`, eventType: "SOME.UNKNOWN" })).handled, false); const duplicate = await reconcilePayPalWebhookEvent(bad); assert.equal(duplicate.duplicate, true); });
  it("maps pending/denied without regressing success and records expired late success", async () => { const f = await fixture(); assert.equal((await reconcilePayPalWebhookEvent(event(f, "PAYMENT.CAPTURE.PENDING"))).handled, true); assert.equal((await prisma.payment.findUnique({ where: { id: f.p.id } }))?.status, PaymentStatus.PROCESSING); assert.equal((await reconcilePayPalWebhookEvent(event(f, "PAYMENT.CAPTURE.DENIED"))).handled, true); assert.equal((await prisma.payment.findUnique({ where: { id: f.p.id } }))?.status, PaymentStatus.FAILED); const g = await fixture(true); const completed = event(g, "PAYMENT.CAPTURE.COMPLETED"); const result = await reconcilePayPalWebhookEvent(completed); assert.equal(result.handled, true); const order = await prisma.order.findUnique({ where: { id: g.o.id } }); const payment = await prisma.payment.findUnique({ where: { id: g.p.id } }); const receipt = await prisma.paymentWebhookEvent.findUnique({ where: { provider_providerEventId: { provider: PaymentProvider.PAYPAL, providerEventId: completed.id } } }); assert.equal(order?.status, OrderStatus.EXPIRED); assert.equal(payment?.status, PaymentStatus.SUCCEEDED); assert.ok(payment?.paidAt); assert.equal(payment?.providerCaptureReference, g.p.providerCaptureReference); assert.equal(receipt?.eventType, "PAYMENT.CAPTURE.COMPLETED"); assert.ok(receipt?.processedAt); assert.match(receipt?.processingError ?? "", /refund\/reconciliation/); });
  it("rejects currency mismatch and does not regress an already successful payment", async () => { const f = await fixture(); const bad = event(f, "PAYMENT.CAPTURE.COMPLETED", { currency: "USD" }); await reconcilePayPalWebhookEvent(bad); assert.equal((await prisma.payment.findUnique({ where: { id: f.p.id } }))?.status, PaymentStatus.PROCESSING); await reconcilePayPalWebhookEvent(event(f, "PAYMENT.CAPTURE.COMPLETED")); await reconcilePayPalWebhookEvent(event(f, "PAYMENT.CAPTURE.DENIED")); assert.equal((await prisma.payment.findUnique({ where: { id: f.p.id } }))?.status, PaymentStatus.SUCCEEDED); });
  it("uses the verified PayPal Order ID fallback and records refunded events only", async () => { const f = await fixture(); await prisma.payment.update({ where: { id: f.p.id }, data: { providerCaptureReference: null } }); const capture = `CAP-${randomUUID()}`; const completed = await reconcilePayPalWebhookEvent({ id: `EV-${randomUUID()}`, eventType: "PAYMENT.CAPTURE.COMPLETED", paypalOrderId: f.p.providerReference, captureId: capture, amount: "12.50", currency: "GBP" }); assert.equal(completed.handled, true); const matched = await prisma.payment.findUnique({ where: { id: f.p.id } }); assert.equal(matched?.providerReference, f.p.providerReference); assert.equal(matched?.providerCaptureReference, capture); const refunded = { id: `EV-${randomUUID()}`, eventType: "PAYMENT.CAPTURE.REFUNDED", captureId: capture, paypalOrderId: f.p.providerReference, amount: "12.50", currency: "GBP" }; assert.equal((await reconcilePayPalWebhookEvent(refunded)).handled, true); assert.equal(await prisma.paymentWebhookEvent.count({ where: { provider: PaymentProvider.PAYPAL, providerEventId: refunded.id } }), 1); assert.equal(await prisma.refund.count({ where: { paymentId: f.p.id } }), 0); });
});
