import assert from "node:assert/strict";
import { afterEach, describe, it } from "node:test";
import { randomUUID } from "node:crypto";
import { Decimal } from "@prisma/client/runtime/client";
import { prisma } from "../prisma/runtime.js";
import { PaymentStatus, PaymentProvider } from "../generated/prisma-client/enums.js";
import { reserveRefundCapacity, finalizeRefundCapacity, releaseRefundCapacity, RefundCapacityExceededError, RefundCapacityNotReservedError } from "../domain/refunds/refundCapacityService.js";
const users: number[] = [], orders: number[] = [];
afterEach(async () => { if (orders.length) await prisma.order.deleteMany({ where: { id: { in: orders } } }); if (users.length) await prisma.user.deleteMany({ where: { id: { in: users } } }); users.length = orders.length = 0; });
async function fixture() { const u = await prisma.user.create({ data: { email: `${randomUUID()}@example.com`, passwordHash: "x" } }); users.push(u.id); const o = await prisma.order.create({ data: { userId: u.id, billingRecipientName: "C", billingLine1: "1", billingCity: "London", billingPostcode: "AA1", billingCountryCode: "GB", deliveryRecipientName: "C", deliveryLine1: "1", deliveryCity: "London", deliveryPostcode: "AA1", deliveryCountryCode: "GB", totalAmount: 100 } }); orders.push(o.id); const p = await prisma.payment.create({ data: { orderId: o.id, amount: 100, currency: "GBP", provider: PaymentProvider.MANUAL, providerReference: `p-${randomUUID()}`, status: PaymentStatus.SUCCEEDED } }); return p; }
describe("Refund capacity foundation", { concurrency: 1 }, () => {
  it("reserves partial capacity and finalizes it", async () => { const p = await fixture(); await reserveRefundCapacity(p.id, 25); assert.equal((await prisma.payment.findUnique({ where: { id: p.id } }))?.reservedRefundAmount.toString(), "25"); await finalizeRefundCapacity(p.id, 25); const value = await prisma.payment.findUnique({ where: { id: p.id } }); assert.equal(value?.reservedRefundAmount.toString(), "0"); assert.equal(value?.refundedAmount.toString(), "25"); });
  it("supports multiple reservations but rejects capacity overflow", async () => { const p = await fixture(); await reserveRefundCapacity(p.id, 40); await reserveRefundCapacity(p.id, 60); await assert.rejects(() => reserveRefundCapacity(p.id, 1), RefundCapacityExceededError); });
  it("releases failure capacity without confirming money", async () => { const p = await fixture(); await reserveRefundCapacity(p.id, 10); await releaseRefundCapacity(p.id, 10); const value = await prisma.payment.findUnique({ where: { id: p.id } }); assert.equal(value?.reservedRefundAmount.toString(), "0"); assert.equal(value?.refundedAmount.toString(), "0"); await assert.rejects(() => releaseRefundCapacity(p.id, 1), RefundCapacityNotReservedError); });
  it("concurrent reservations that exceed capacity allow exactly one winner", async () => { const p = await fixture(); const results = await Promise.allSettled([reserveRefundCapacity(p.id, 70), reserveRefundCapacity(p.id, 70)]); assert.equal(results.filter((r) => r.status === "fulfilled").length, 1); assert.equal(results.filter((r) => r.status === "rejected" && r.reason instanceof RefundCapacityExceededError).length, 1); assert.equal((await prisma.payment.findUnique({ where: { id: p.id } }))?.reservedRefundAmount.toString(), "70"); });
  it("includes confirmed refunded money when checking remaining capacity", async () => { const p = await fixture(); await prisma.payment.update({ where: { id: p.id }, data: { refundedAmount: 40, reservedRefundAmount: 30 } }); await assert.rejects(() => reserveRefundCapacity(p.id, 31), RefundCapacityExceededError); await reserveRefundCapacity(p.id, 30); });
  it("cannot finalize or release more than the current reservation", async () => { const p = await fixture(); await reserveRefundCapacity(p.id, 10); await assert.rejects(() => finalizeRefundCapacity(p.id, 11), RefundCapacityNotReservedError); await assert.rejects(() => releaseRefundCapacity(p.id, 11), RefundCapacityNotReservedError); const value = await prisma.payment.findUnique({ where: { id: p.id } }); assert.equal(value?.reservedRefundAmount.toString(), "10"); });
  it("persists a PROCESSING provider refund with a unique idempotency key", async () => { const p = await fixture(); const refund = await prisma.refund.create({ data: { orderId: p.orderId, paymentId: p.id, amount: 10, currency: "GBP", provider: PaymentProvider.PAYPAL, providerReference: `pending-${randomUUID()}`, refundIdempotencyKey: `refund-${randomUUID()}`, status: "PROCESSING", performedByUserId: users[0] } }); assert.equal(refund.status, "PROCESSING"); await assert.rejects(() => prisma.refund.create({ data: { orderId: p.orderId, paymentId: p.id, amount: 1, currency: "GBP", provider: PaymentProvider.PAYPAL, providerReference: `pending-${randomUUID()}`, refundIdempotencyKey: refund.refundIdempotencyKey, status: "PROCESSING", performedByUserId: users[0] } })); });
  it("does not change Order state while moving refund capacity", async () => { const p = await fixture(); const before = await prisma.order.findUnique({ where: { id: p.orderId }, select: { status: true } }); await reserveRefundCapacity(p.id, 10); await finalizeRefundCapacity(p.id, 10); const after = await prisma.order.findUnique({ where: { id: p.orderId }, select: { status: true } }); assert.deepEqual(after, before); });
});
