import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { afterEach, describe, it } from "node:test";
import { Decimal } from "@prisma/client/runtime/client";
import { prisma } from "../prisma/runtime.js";
import { PaymentProvider, PaymentStatus, RefundProvider, RefundStatus } from "../generated/prisma-client/enums.js";
import { createOrReuseStripeRefund, StripeRefundProviderError, StripeRefundValidationError, setStripeRefundClientForTests, type StripeRefundClient } from "../domain/refunds/stripeRefundService.js";

const users: number[] = [], orders: number[] = [];
afterEach(async () => { if (orders.length) await prisma.order.deleteMany({ where: { id: { in: orders } } }); if (users.length) await prisma.user.deleteMany({ where: { id: { in: users } } }); users.length = orders.length = 0; });
async function fixture(amount = "100.00", provider = PaymentProvider.STRIPE, status = PaymentStatus.SUCCEEDED) { const u = await prisma.user.create({ data: { email: `${randomUUID()}@example.com`, passwordHash: "hash" } }); users.push(u.id); const o = await prisma.order.create({ data: { userId: u.id, billingRecipientName: "C", billingLine1: "1", billingCity: "London", billingPostcode: "AA1", billingCountryCode: "GB", deliveryRecipientName: "C", deliveryLine1: "1", deliveryCity: "London", deliveryPostcode: "AA1", deliveryCountryCode: "GB", totalAmount: new Decimal(amount) } }); orders.push(o.id); const p = await prisma.payment.create({ data: { orderId: o.id, amount: new Decimal(amount), currency: "GBP", provider, providerReference: `pi_${randomUUID()}`, status } }); return { u, o, p }; }
function fake(status = "succeeded", amount = "1000", currency = "gbp", fail = false) { const calls: Array<{ input: any; options: any }> = []; const client: StripeRefundClient = { createRefund: async (input, options) => { calls.push({ input, options }); if (fail) throw new Error("secret provider body"); return { id: `re_${randomUUID()}`, amount: Number(amount), currency, status, payment_intent: input.payment_intent as string, metadata: input.metadata ?? {} } as any; } }; return { calls, restore: setStripeRefundClientForTests(client) }; }
describe("Stripe refund service", { concurrency: 1 }, () => {
  it("creates and finalizes an authoritative full refund", async () => { const f = await fixture(); const c = fake("succeeded", "10000"); const result = await createOrReuseStripeRefund(f.o.id, f.p.id, 100, "requested_by_customer", f.u.id); assert.equal(result.status, RefundStatus.SUCCEEDED); assert.equal(result.provider, RefundProvider.STRIPE); assert.equal(c.calls[0].input.payment_intent, f.p.providerReference); assert.equal(c.calls[0].input.amount, 10000); assert.deepEqual(c.calls[0].input.metadata, { local_refund_id: String(result.id), order_id: String(f.o.id) }); assert.ok(c.calls[0].options.idempotencyKey); const p = await prisma.payment.findUnique({ where: { id: f.p.id } }); assert.equal(p?.refundedAmount.toString(), "100"); assert.equal(p?.reservedRefundAmount.toString(), "0"); assert.match(result.providerReference, /^re_/); c.restore(); });
  it("supports distinct partial refunds and blocks cumulative over-refund", async () => { const f = await fixture(); const a = fake("succeeded", "3000"); const first = await createOrReuseStripeRefund(f.o.id, f.p.id, 30, undefined, f.u.id); a.restore(); const b = fake("succeeded", "3000"); const second = await createOrReuseStripeRefund(f.o.id, f.p.id, 30, undefined, f.u.id); assert.notEqual(first.id, second.id); assert.notEqual(first.refundIdempotencyKey, second.refundIdempotencyKey); assert.equal(b.calls.length, 1); b.restore(); await assert.rejects(() => createOrReuseStripeRefund(f.o.id, f.p.id, 50, undefined, f.u.id)); });
  it("keeps pending and requires_action refunds processing", async () => { for (const state of ["pending", "requires_action"]) { const f = await fixture(); const c = fake(state); const result = await createOrReuseStripeRefund(f.o.id, f.p.id, 10, undefined, f.u.id); assert.equal(result.status, RefundStatus.PROCESSING); assert.equal((await prisma.payment.findUnique({ where: { id: f.p.id } }))?.reservedRefundAmount.toString(), "10"); c.restore(); } });
  it("releases capacity on definitive failure", async () => { const f = await fixture(); const c = fake("failed"); const result = await createOrReuseStripeRefund(f.o.id, f.p.id, 10, undefined, f.u.id); assert.equal(result.status, RefundStatus.FAILED); const p = await prisma.payment.findUnique({ where: { id: f.p.id } }); assert.equal(p?.refundedAmount.toString(), "0"); assert.equal(p?.reservedRefundAmount.toString(), "0"); c.restore(); });
  it("preserves the same attempt and idempotency key after timeout", async () => { const f = await fixture(); const first = fake("succeeded", "1000", "gbp", true); await assert.rejects(() => createOrReuseStripeRefund(f.o.id, f.p.id, 10, undefined, f.u.id), StripeRefundProviderError); first.restore(); const pending = await prisma.refund.findFirst({ where: { paymentId: f.p.id } }); const second = fake(); const result = await createOrReuseStripeRefund(f.o.id, f.p.id, 999, undefined, f.u.id, undefined, pending!.id); assert.equal(result.id, pending!.id); assert.equal(second.calls[0].options.idempotencyKey, pending?.refundIdempotencyKey); assert.equal(second.calls[0].input.amount, 1000); assert.equal((await prisma.payment.findUnique({ where: { id: f.p.id } }))?.refundedAmount.toString(), "10"); second.restore(); });
  it("does not call Stripe for terminal or invalid attempts", async () => { const f = await fixture(); const c = fake(); const done = await createOrReuseStripeRefund(f.o.id, f.p.id, 10, undefined, f.u.id); c.restore(); const retry = fake(); const result = await createOrReuseStripeRefund(f.o.id, f.p.id, 10, undefined, f.u.id, undefined, done.id); assert.equal(result.id, done.id); assert.equal(retry.calls.length, 0); retry.restore(); const failed = await fixture(); const failedClient = fake("failed", "1000"); const failedResult = await createOrReuseStripeRefund(failed.o.id, failed.p.id, 10, undefined, failed.u.id); failedClient.restore(); const retryFailed = fake(); await assert.rejects(() => createOrReuseStripeRefund(failed.o.id, failed.p.id, 10, undefined, failed.u.id, undefined, failedResult.id), StripeRefundValidationError); assert.equal(retryFailed.calls.length, 0); retryFailed.restore(); });
  it("keeps capacity on provider response mismatch", async () => { const f = await fixture(); const c = fake("succeeded", "999", "usd"); await assert.rejects(() => createOrReuseStripeRefund(f.o.id, f.p.id, 10, undefined, f.u.id), StripeRefundValidationError); const p = await prisma.payment.findUnique({ where: { id: f.p.id } }); assert.equal(p?.refundedAmount.toString(), "0"); assert.equal(p?.reservedRefundAmount.toString(), "10"); c.restore(); });
});
