import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { afterEach, describe, it } from "node:test";
import { Decimal } from "@prisma/client/runtime/client";
import { prisma } from "../prisma/runtime.js";
import { PaymentProvider, PaymentStatus, RefundProvider, RefundStatus } from "../generated/prisma-client/enums.js";
import { reconcileStripeRefundEvent } from "../domain/payments/stripeReconciliationService.js";
const users: number[] = [], orders: number[] = [], payments: number[] = [], refunds: number[] = [];
afterEach(async () => { if (refunds.length) await prisma.refund.deleteMany({ where: { id: { in: refunds } } }); if (payments.length) await prisma.payment.deleteMany({ where: { id: { in: payments } } }); if (orders.length) await prisma.order.deleteMany({ where: { id: { in: orders } } }); if (users.length) await prisma.user.deleteMany({ where: { id: { in: users } } }); refunds.length = payments.length = orders.length = users.length = 0; });
async function fixture() { const user = await prisma.user.create({ data: { email: `${randomUUID()}@example.com`, passwordHash: "hash" } }); users.push(user.id); const order = await prisma.order.create({ data: { userId: user.id, billingRecipientName: "C", billingLine1: "1", billingCity: "London", billingPostcode: "AA1", billingCountryCode: "GB", deliveryRecipientName: "C", deliveryLine1: "1", deliveryCity: "London", deliveryPostcode: "AA1", deliveryCountryCode: "GB", totalAmount: 10 } }); orders.push(order.id); const payment = await prisma.payment.create({ data: { orderId: order.id, amount: 10, currency: "GBP", provider: PaymentProvider.STRIPE, providerReference: `pi_${randomUUID()}`, status: PaymentStatus.SUCCEEDED, paidAt: new Date(), reservedRefundAmount: 5 } }); payments.push(payment.id); const refund = await prisma.refund.create({ data: { orderId: order.id, paymentId: payment.id, amount: 5, currency: "GBP", provider: RefundProvider.STRIPE, providerReference: `pending:${randomUUID()}`, refundIdempotencyKey: `refund-${randomUUID()}`, status: RefundStatus.PROCESSING, performedByUserId: user.id } }); refunds.push(refund.id); return { order, payment, refund }; }
describe("Stripe refund webhook reconciliation", { concurrency: 1 }, () => {
  it("finalizes metadata-correlated success once", async () => { const f = await fixture(); const event = { id: randomUUID(), type: "refund.created" as const, refundId: `re_${randomUUID()}`, paymentIntentId: f.payment.providerReference, amount: 500, currency: "gbp", status: "succeeded", metadata: { local_refund_id: String(f.refund.id), order_id: String(f.order.id) } }; await reconcileStripeRefundEvent(event); await reconcileStripeRefundEvent({ ...event, id: randomUUID(), type: "refund.updated" }); const p = await prisma.payment.findUnique({ where: { id: f.payment.id } }); const r = await prisma.refund.findUnique({ where: { id: f.refund.id } }); assert.equal(r?.status, RefundStatus.SUCCEEDED); assert.equal(p?.refundedAmount.toString(), "5"); assert.equal(p?.reservedRefundAmount.toString(), "0"); });
  it("does not finalize wrong or malformed correlation", async () => { const f = await fixture(); const before = await prisma.refund.findUnique({ where: { id: f.refund.id } }); await reconcileStripeRefundEvent({ id: randomUUID(), type: "refund.created", refundId: `re_${randomUUID()}`, paymentIntentId: "pi_wrong", amount: 500, currency: "usd", status: "succeeded", metadata: { local_refund_id: "bad" } }); const p = await prisma.payment.findUnique({ where: { id: f.payment.id } }); const after = await prisma.refund.findUnique({ where: { id: f.refund.id } }); assert.equal(p?.refundedAmount.toString(), "0"); assert.equal(p?.reservedRefundAmount.toString(), "5"); assert.equal(after?.status, RefundStatus.PROCESSING); assert.equal(after?.providerReference, before?.providerReference); });
  it("releases capacity once for failed refunds and keeps pending attempts held", async () => { const f = await fixture(); const failed = { id: randomUUID(), type: "refund.failed" as const, refundId: `re_${randomUUID()}`, paymentIntentId: f.payment.providerReference, amount: 500, currency: "gbp", status: "failed", metadata: { local_refund_id: String(f.refund.id) } }; await reconcileStripeRefundEvent(failed); await reconcileStripeRefundEvent({ ...failed, id: randomUUID(), type: "refund.updated" }); const after = await prisma.payment.findUnique({ where: { id: f.payment.id } }); assert.equal(after?.reservedRefundAmount.toString(), "0"); assert.equal(after?.refundedAmount.toString(), "0"); assert.equal((await prisma.refund.findUnique({ where: { id: f.refund.id } }))?.status, RefundStatus.FAILED); const pending = await fixture(); await reconcileStripeRefundEvent({ id: randomUUID(), type: "refund.created", refundId: `re_${randomUUID()}`, paymentIntentId: pending.payment.providerReference, amount: 500, currency: "gbp", status: "pending", metadata: { local_refund_id: String(pending.refund.id) } }); const held = await prisma.payment.findUnique({ where: { id: pending.payment.id } }); assert.equal(held?.reservedRefundAmount.toString(), "5"); assert.equal((await prisma.refund.findUnique({ where: { id: pending.refund.id } }))?.status, RefundStatus.PROCESSING); });
  it("does not regress success and does not double-finalize webhook-first success", async () => { const f = await fixture(); const event = { id: randomUUID(), type: "refund.created" as const, refundId: `re_${randomUUID()}`, paymentIntentId: f.payment.providerReference, amount: 500, currency: "gbp", status: "succeeded", metadata: { local_refund_id: String(f.refund.id) } }; await reconcileStripeRefundEvent(event); await reconcileStripeRefundEvent({ ...event, id: randomUUID(), type: "refund.failed", status: "failed" }); const payment = await prisma.payment.findUnique({ where: { id: f.payment.id } }); assert.equal(payment?.refundedAmount.toString(), "5"); assert.equal(payment?.reservedRefundAmount.toString(), "0"); assert.equal((await prisma.refund.findUnique({ where: { id: f.refund.id } }))?.status, RefundStatus.SUCCEEDED); });
  it("isolates same-amount refunds and accepts expanded PaymentIntent identity", async () => { const a = await fixture(); const b = await fixture(); const shared = `re_${randomUUID()}`; const base = (f: Awaited<ReturnType<typeof fixture>>, id: string) => ({ id, type: "refund.created" as const, refundId: `re_${randomUUID()}`, paymentIntentId: f.payment.providerReference, amount: 500, currency: "GBP", status: "succeeded", metadata: { local_refund_id: String(f.refund.id), order_id: String(f.order.id) } }); await reconcileStripeRefundEvent(base(a, randomUUID())); await reconcileStripeRefundEvent(base(b, randomUUID())); assert.equal((await prisma.payment.findUnique({ where: { id: a.payment.id } }))?.refundedAmount.toString(), "5"); assert.equal((await prisma.payment.findUnique({ where: { id: b.payment.id } }))?.refundedAmount.toString(), "5"); const expanded = base(a, randomUUID()); await reconcileStripeRefundEvent(expanded); const unchanged = await prisma.payment.findUnique({ where: { id: a.payment.id } }); assert.equal(unchanged?.refundedAmount.toString(), "5"); assert.notEqual(shared, ""); });
  it("rejects null PaymentIntent and conflicting provider reference without accounting movement", async () => { const f = await fixture(); await prisma.refund.update({ where: { id: f.refund.id }, data: { providerReference: `re_existing_${randomUUID()}` } }); await reconcileStripeRefundEvent({ id: randomUUID(), type: "refund.created", refundId: `re_other_${randomUUID()}`, paymentIntentId: undefined, amount: 500, currency: "GBP", status: "succeeded", metadata: { local_refund_id: String(f.refund.id) } }); const p = await prisma.payment.findUnique({ where: { id: f.payment.id } }); assert.equal(p?.refundedAmount.toString(), "0"); assert.equal(p?.reservedRefundAmount.toString(), "5"); assert.equal((await prisma.refund.findUnique({ where: { id: f.refund.id } }))?.status, RefundStatus.PROCESSING); });
});
