import assert from "node:assert/strict";
import { afterEach, describe, it } from "node:test";
import { randomUUID } from "node:crypto";
import { Decimal } from "@prisma/client/runtime/client";
import { prisma } from "../prisma/runtime.js";
import { PaymentProvider, PaymentStatus } from "../generated/prisma-client/enums.js";
import { reconcileStripePaymentEvent } from "../domain/payments/stripeReconciliationService.js";

const users: number[] = [], orders: number[] = [], payments: number[] = [];
afterEach(async () => { if (payments.length) await prisma.payment.deleteMany({ where: { id: { in: payments } } }); if (orders.length) await prisma.order.deleteMany({ where: { id: { in: orders } } }); if (users.length) await prisma.user.deleteMany({ where: { id: { in: users } } }); users.length = orders.length = payments.length = 0; });
async function fixture(expired = false) { const user = await prisma.user.create({ data: { email: `${randomUUID()}@example.com`, passwordHash: "hash", emailVerified: true } }); users.push(user.id); const order = await prisma.order.create({ data: { userId: user.id, status: expired ? "EXPIRED" : "PENDING", billingRecipientName: "C", billingLine1: "1 Street", billingCity: "London", billingPostcode: "SW1A 1AA", billingCountryCode: "GB", deliveryRecipientName: "C", deliveryLine1: "1 Street", deliveryCity: "London", deliveryPostcode: "SW1A 1AA", deliveryCountryCode: "GB", totalAmount: new Decimal("12.50") } }); orders.push(order.id); const payment = await prisma.payment.create({ data: { orderId: order.id, amount: new Decimal("12.50"), currency: "GBP", provider: PaymentProvider.STRIPE, providerReference: `pi_${randomUUID()}`, status: PaymentStatus.PROCESSING, idempotencyKey: `key-${randomUUID()}` } }); payments.push(payment.id); return { user, order, payment }; }
function event(paymentId: string, id = randomUUID(), type: "payment_intent.succeeded" | "payment_intent.payment_failed" | "payment_intent.canceled" = "payment_intent.succeeded", amount = 1250, currency = "gbp") { return { id, type, paymentIntentId: paymentId, amount, currency }; }

describe("Stripe reconciliation", () => {
  it("marks a matching success final and deduplicates delivery", async () => { const f = await fixture(); const e = event(f.payment.providerReference); assert.deepEqual(await reconcileStripePaymentEvent(e), { duplicate: false, handled: true }); const payment = await prisma.payment.findUnique({ where: { id: f.payment.id } }); assert.equal(payment?.status, "SUCCEEDED"); assert.ok(payment?.paidAt); assert.deepEqual(await reconcileStripePaymentEvent(e), { duplicate: true, handled: true }); });
  it("maps failures/cancellation without regressing success", async () => { const f = await fixture(); await reconcileStripePaymentEvent(event(f.payment.providerReference, randomUUID(), "payment_intent.payment_failed")); assert.equal((await prisma.payment.findUnique({ where: { id: f.payment.id } }))?.status, "FAILED"); const g = await fixture(); await reconcileStripePaymentEvent(event(g.payment.providerReference, randomUUID(), "payment_intent.canceled")); assert.equal((await prisma.payment.findUnique({ where: { id: g.payment.id } }))?.status, "CANCELED"); await reconcileStripePaymentEvent(event(g.payment.providerReference, randomUUID(), "payment_intent.succeeded")); await reconcileStripePaymentEvent(event(g.payment.providerReference, randomUUID(), "payment_intent.payment_failed")); assert.equal((await prisma.payment.findUnique({ where: { id: g.payment.id } }))?.status, "SUCCEEDED"); });
  it("does not finalize mismatched or unknown payments", async () => { const f = await fixture(); await reconcileStripePaymentEvent(event(f.payment.providerReference, randomUUID(), "payment_intent.succeeded", 999)); assert.equal((await prisma.payment.findUnique({ where: { id: f.payment.id } }))?.status, "PROCESSING"); assert.deepEqual(await reconcileStripePaymentEvent(event("pi_unknown")), { duplicate: false, handled: false }); });
  it("keeps expired orders expired while recording late success reconciliation", async () => { const f = await fixture(true); const lateId = randomUUID(); await reconcileStripePaymentEvent(event(f.payment.providerReference, lateId)); const order = await prisma.order.findUnique({ where: { id: f.order.id } }); const payment = await prisma.payment.findUnique({ where: { id: f.payment.id } }); const receipt = await prisma.paymentWebhookEvent.findFirst({ where: { providerEventId: lateId } }); assert.equal(order?.status, "EXPIRED"); assert.equal(payment?.status, "SUCCEEDED"); assert.equal(payment?.paidAt !== null, true); assert.ok(receipt); assert.match(receipt.processingError ?? "", /refund\/reconciliation/); });
});
